### PR TITLE
Adapt to breaking changes in nightly

### PR DESCRIPTION
**Pull request by calops**
* A new parameter of type `Arena*` has been added to some nvim API functions, this caused a crash anytime one of those functions would yield an error (since the new parameter has been inserted before the `err` one)
* New fields in the structs for highlights options
* New fields in the structs for windows options

### CODE REVIEW

**Comment by calops** [comment]
Note: the `api::global::hl_underline` fails on Linux still (panics because of an underflow error somehow), but I can't for the life of me figure out what's happening. The function `nvim_get_hl_by_name` arbitrarily (but deterministically) causes the panic if we try to look up the HL we just defined. Sometimes it panics for other already defined groups as well, but not all. And sometimes it works but the panic happens later on (???).

Sounds like a memory corruption somewhere but I can't figure any of this out.

**Comment by noib3** [comment]
Thanks I'll review this between Monday and Tuesday.

Unfortunately I don't have access to a linux machine to test `nvim_get_hl_by_name` on, do you know the first Neovim commit that caused it to fail in that way?

**Comment by calops** [comment]
I think the PR shouldn't be merged until that memory corruption is fixed. Now that I think about it, maybe the problem comes from my changes in `set_highlight.rs`? I'll have to do some more testing.

The responsible neovim commit is [this one](https://github.com/neovim/neovim/commit/ba8be7446d440053b24358046e8e4033e3447633).

**Comment by calops** [comment]
OK, scratch that, sometimes it happens with other namespaces too. There's obviously a memory corruption somewhere, and it comes from `nvim_set_hl` (but only messes things up *after* getting out of this function, randomly). I can't find out any more than this and it's driving me crazy.

**Comment by noib3** [comment]
I've updated [38c91c0](https://github.com/noib3/nvim-oxi/pull/100/commits/38c91c0aed99ebd510d10882b74281b4ed070824) to include the `Arena` parameter when compiling for 0.8 as well as nightly. 

I can now reproduce the segfault caused by `nvim_get_hl_by_name` on macOS using Neovim 0.8.3.

**Comment by noib3** [comment]
`nvim_get_hl_by_id` and `nvim_get_hl_by_name` are the last 2 remaining functions that are still segfaulting on both Neovim 0.8.3 and nightly, so I think I'm gonna merge this.

I'm not familiar with arena allocation but I think the error is caused by the `Arena` that we're passing, possibly somewhere in [this code path](https://github.com/neovim/neovim/blob/129264dbb41404b94b835baadfc3fa25ffac3d3e/src/nvim/highlight.c#L804).

**Comment by calops** [comment]
> I'm not familiar with arena allocation but I think the error is caused by the Arena that we're passing, possibly somewhere in [this code path](https://github.com/neovim/neovim/blob/129264dbb41404b94b835baadfc3fa25ffac3d3e/src/nvim/highlight.c#L804).

That was my suspicion as well, but I've looked into it for a while and couldn't see anything wrong. I've even tried passing null pointers everywhere instead of empty arenas (which should work as all the relevant functions handle this case properly, as far as I can tell), and the behavior is the exact same.

**Comment by noib3** [comment]
I think I've figured this out, I'm cleaning up a bit before pushing the fix.

**Comment by noib3** [comment]
> I think I've figured this out, I'm cleaning up a bit before pushing the fix.

fixed by 9b36ad076af949448f927d66f044c51d97e086ae.

**Pull request merged**
