### PR TITLE
install neovim on github workers to make tests work

### PR DESCRIPTION
**Pull request by shift-d**

### CODE REVIEW

**Comment by shift-d** [comment]
#12 moment on windows, it seems, @noib3

**Comment by shift-d** [comment]
alright, I will look at mlua tests later, since im going to sleep now, but right now it seems that i found a weird solution that will probably work. i basically ignore every unresolved external symbol error in linker

**Comment by shift-d** [comment]
i will push it to this branch if it will work

**Comment by shift-d** [comment]
hmmm

**Comment by shift-d** [comment]
изображение
good news: it fixed the issue, but now there's another error

**Comment by noib3** [comment]
> good news: it fixed the issue, but now there's another error

That's an easy fix, I thought Windows would behave like macOS and Linux when building a library in that in prepends a `lib` to the name of the compiled artifact, but apparently it doesn't. Will fix it later, for now you can just rename `oxi_tests.dll` to `liboxi_tests.dll`.

Btw, the contents of `/.cargo/config` should probably be appended to `/oxi-tests/.cargo/config`. A `cargo build` at the root of the repo is expected to fail, what matters is that the `oxi-tests` crate (which depends on `nvim-oxi`) builds.

**Pull request merged**
