### PR TITLE
Fix linking issues on Windows

### PR DESCRIPTION
**Pull request by searleser97**
closes https://github.com/noib3/nvim-oxi/issues/77, https://github.com/noib3/nvim-oxi/issues/120

### CODE REVIEW

**Comment by noib3** [comment]
I've added those linker flags to the `.cargo/config.toml` file to see if it would fix CI on Windows.

Unfortunately all the integration tests fail because `Neovim exited with non-zero exit code: -1073741819`, which from what I call tell means that some [access was denied](https://www.scivision.dev/windows-exit-code-1073741819/#:~:text=This%20code%20means%20%E2%80%9CAccess%20denied,or%20locking%20binary%20files%20needed.).

Does the same happen to you locally if you do

```
cargo build --features=neovim-nightly
cd tests
cargo test --features=neovim-nightly
```

?

**Comment by searleser97** [comment]
> I've added those linker flags to the `.cargo/config.toml` file to see if it would fix CI on Windows.
> 
> Unfortunately all the integration tests fail because `Neovim exited with non-zero exit code: -1073741819`, which from what I call tell means that some [access was denied](https://www.scivision.dev/windows-exit-code-1073741819/#:~:text=This%20code%20means%20%E2%80%9CAccess%20denied,or%20locking%20binary%20files%20needed.).
> 
> Does the same happen to you locally if you do
> 
> ```
> cd tests
> cargo build --features=neovim-nightly
> cargo test --features=neovim-nightly
> ```
> 
> ?

Looks like I still need to add the `build.rs` mentioned in this comment to make it work. So, looks like we need to have a lua51.dll and lua.lib file at the time of testing in CI

**Comment by noib3** [comment]
So it works locally if you add that `build.rs` to `tests`? Seems weird since that's only relevant at build time, and building already works in CI.

**Comment by noib3** [comment]
Closed by #149.

**Pull request closed without merging**
