### PR TITLE
Fix Windows Dynamic Linking

### LINKED ISSUE #125: Crash when loading the example plugin on Windows
Hello,
I am using the crate setup example from the repo and Neovim crashes when loading the plugin DLL file by requiring the module. I am copying the DLL directly to NeoVim's `bin` directory.

The nvim process crashes with virtually no way to debug it.
I tried the latest git version of `nvim-oxi`.
I am on Windows, I added the `/force:UNRESOLVED` flags to my cargo config:
```toml
[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C", "link-arg=/FORCE:UNRESOLVED",
]

[target.aarch64-pc-windows-msvc]
rustflags = [
  "-C", "link-arg=/FORCE:UNRESOLVED",
]
```

### PR DESCRIPTION
**Pull request by AregevDev**
Hello,

Linking against the symbol definitions explicitly instead of using `/force:unresolved` fixes the segfaults. The examples work as expected. Note that the lib definitions, taken from a 0.9 source build, haven't been tested on a nightly NeoVim.

Fixes #125

### CODE REVIEW

**Comment by noib3** [comment]
Could you remove the first 2 commits and cherry-pick 6c8c54a6c2e57d871bb6f211b0bc78945d892f73 to see if this fixes CI on Windows?

Also, what about [this](https://github.com/noib3/nvim-oxi/issues/125#issuecomment-1984356052)?

**Comment by AregevDev** [comment]
I removed the first two commits, I can't cherry-pick the commit you sent. I'll add the Windows CI to the build script and commit again.

**Comment by melMass** [comment]
Thanks I used the libs from an earlier version of this PR for [echo](https://github.com/melMass/echo.nvim), would this new refactoring do it at build time? I'm still trying to figure out how to properly bundle it. For now, I think I'll build all platforms in GH actions and use a build step in lazy to fetch the releases from Github, I'm not sure that's very common...

**Comment by noib3** [comment]
Closed by #149.

**Pull request closed without merging**
