### PR TITLE
api-autocmd bindings

### LINKED ISSUE #5: Implement all functions under `:h api-autocmd`

### PR DESCRIPTION
**Pull request by MordechaiHadad**
Wanted to know if what I wrote is actually good or not.

resolves #5

### CODE REVIEW

**Comment by MordechaiHadad** [comment]
@noib3 are the changes satisfactory?

**Comment by noib3** [comment]
a) don't change the return value of the ffi binding to `u32`, change `error.into_err_or_else(|| result)` to `   error.into_err_or_else(|| result.try_into().expect("always positive")`;

b) like I said, *always* test a binding once you've implemented it by adding a test to `oxi-tests`. In this case you'll realize that it cannot work because there's no way for users to create a `CreateAugroupOpts` since the `clear` field is private. The way to get around it is to use the builder pattern:

```rust
#[derive(Clone, Debug, Default, Builder)]
#[builder(default)]
pub struct CreateAugroupOpts {
     #[builder(setter(strip_option))]
     clear: Option<bool>,
 }
```

c) once you do you'll see that it still doesn't work. I'll spare you the details but basically the `opts` field of `nvim_create_augroup` is not a `Dictionary` but a struct that Neovim generates at build time (in this case called `KeyDict_create_augroup`.

My advice would be to start with easier bindings. In general all functions that have an `opts` are somewhat non trivial to write bindings for.  If you want to work on the `autocmd` module I'd look into `nvim_del_autocmd`, `nvim_del_augroup_by_name` or `nvim_del_augroup_by_id`.

**Comment by MordechaiHadad** [comment]
a) Alright thanks for that.
b) Didn't add any tests *yet..* since I'm still trying to understand how this works
c) Fair enough.

Thank you @noib3

**Comment by MordechaiHadad** [comment]
@noib3 hello I have added a test in oxi-tests, how can I run a specific test?
this testing setup is a bit different to what I am used to.

**Comment by noib3** [comment]
Unfortunately there's currently no way to run a specific test. [This](https://users.rust-lang.org/t/how-do-you-test-a-library-imported-by-another-program/76483) is why. Basically you'd need to compile each test as a `cdylib` and spin up a Neovim session that loads and runs the library, which I don't think is possible.

**Comment by MordechaiHadad** [comment]
@noib3 ouch... I can't really test my test then due to a test that fails in `src/api/buffer.rs:35`

**Comment by noib3** [comment]
CI is green so there shouldn't be any tests failing. What OS are you on and what does the error msg say?

**Comment by MordechaiHadad** [comment]
I am running WSL Arch for my OS
This is the error message i get:
```
warning: `oxi-tests` (lib test) generated 1 warning
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running unittests (target/debug/deps/oxi_tests-9bec374157575f9f)

running 1 test
test test_all ... FAILED

failures:

---- test_all stdout ----
thread 'test_all' panicked at 'assertion failed: `(left == right)`
  left: `"thread '<unnamed>' panicked at 'assertion failed: res.is_ok()', src/api/buffer.rs:35:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\nAny { .. }\n"`,
 right: `""`', src/lib.rs:64:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_all

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass '--lib'
```

**Comment by noib3** [comment]
Don't forget to `git pull`!

**Comment by MordechaiHadad** [comment]
@noib3 👀 now I'm getting that `nvim_types::error::Error` is a private module?

**Comment by noib3** [comment]
What branch are you pulling from? Try doing a `git clone https://github.com/noib3/nvim-oxi && cd nvim-oxi && cargo check`, there shouldn't be any errors.

**Comment by MordechaiHadad** [comment]
@noib3 I am using a cloned local version of my fork + upstream remote pointing to ur repo, and I pull from the upstream master branch.
The errors come from my code that complains about types being private.

**Comment by noib3** [comment]
the autocmd bindings have already been implemented so I'm gonna close this

**Comment by MordechaiHadad** [comment]
Fair enough I was quite busy, good to see it's implemented

**Pull request closed without merging**
