### PR TITLE
feat(snapshot): testing examples

### PR DESCRIPTION
**Pull request by zjp-CN**
1. add testing bash scripts for examples
2. add `src/test.rs` which takes snapshots for:
* calc & mechanic: succeeded
* mlua & api: failed #54

---
And
* fix the mechanic example
* add mlua `vendored` feature  in the absence of Lua

### CODE REVIEW

**Comment by zjp-CN** [comment]
You can use these cmds in `examples` dir:
* `cargo test`
* `cargo insta test --review` to update all the snapshots (except tagged with `#[ignored]` ones).
* `cargo insta test --review -- test_fn_name` to update `test_fn_name` only

**Comment by zjp-CN** [comment]
Will you consider merging this PR?

**Comment by noib3** [comment]
Sorry I have yet to review it, will try to look at it this weekend.

**Comment by zjp-CN** [comment]
I'm gonna close this and put up a new PR to test examples.

**Pull request closed without merging**
